apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: boardgame
spec:
  selector:
    app: boardgame
  ports:
    # Below Port number is a service port number
    - port: 80
      # Below targetPort is a Container Port number
      targetPort: 8080
