apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: boardgame
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - protocol: "TCP"
    # Below Port number is a service port number
      port: 80
    # Below targetPort is a Container Port number
      targetPort: 8080
